replicaCount: 1

imagePullSecrets: []
image: {}
nameOverride: ""
fullnameOverride: ""

domainName: ""
userRegistration: false

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: ""
  annotations: {}
  hosts:
  tls: []

resources: {}

autoscaling:
  enabled: false

nodeSelector: {}

tolerations: []

affinity: {}

storage:
  data:
    customVolume: false
  images:
    customVolume: false